### ISSUE TITLE
Docker client error with azure

### ISSUE THREAD

**Issue by ryanlovett** [yuvipanda/hubploy#26]
@tjcrone I've tested azure registries but I can't get `client.images.get_registry_data(image_spec)` calls to succeed. [imagebuilder.py#L18](https://github.com/yuvipanda/hubploy/blob/master/hubploy/imagebuilder.py#L18) throws

```
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http+docker://localhost/v1.35/distribution/my_image_spec:tag/json
```

I'm wondering if I'm missing some other initial setup or configuration since gcr is the the only registry that responds to `client.images.get_registry_data(image_spec)`.

**Comment by ryanlovett** [comment]
I created a smaller test case and I don't think this is due to anything auth related. Sorry for the noise.

**Comment by tjcrone** [comment]
Hi @ryanlovett. Although the error message you are seeing is surprisingly unhelpful, I think this is something that I might have seen during testing. Your error is occurring during a docker SDK call and I think this issue is likely related to Azure not allowing anonymous read-only access to containers. See this post for more information: https://stackoverflow.com/questions/47425337/read-only-anonymous-access-to-azure-container-registry. It is apparently possible to enable anonymous access, but I have not yet tried. We could potentially add authentication to this function, but there are downsides to doing this. We do need a solution though. I think we should wait to see what @yuvipanda suggests at this stage. In the meantime, if you are able to, can you try to enable anonymous read-only pull access to your image? Please let me know what you find. Thanks!

**Comment by tjcrone** [comment]
Just saw that you closed this. Okay, thanks for the update. Let us know if there are any other issues. Thanks!
