### ISSUE TITLE
Optionally use of helm3 instead of helm2

### ISSUE THREAD

**Issue by scottyhq** [yuvipanda/hubploy#40]
I'd like to use helm3 for managing a new hub. The hubploy dockerfile just installs helm 2.14.3, but has a note about multiple versions specified at runtime.
https://github.com/yuvipanda/hubploy/blob/master/Dockerfile#L23 

Happy to follow up with a PR, but need a bit of guidance first. Perhaps this would also require a new file `hubploy/helm3.py` to account for potential syntax differences with helm3 commands?

**Comment by arokem** [comment]
I might be missing the point, but I believe that you can already use helm3. See this deployment: https://github.com/learning-2-learn/l2lhub-deployment/blob/staging/.github/workflows/deploy.yaml. However, note the somewhat iffy use of the `dev` image.

**Comment by yuvipanda** [comment]
The only thing helm3 seems to need extra is namespace creation inside hubploy. We might want to do this regardless anyway if the namespace does not exist. We will then have to ship multiple versions of helm in the image, and pick one based on the version of helm installed in the cluster.

**Comment by yuvipanda** [comment]
You can now set `HELM_EXECUTABLE` env var to point to a helm3 binary.

Other things we need are:

1. Permissions helm3 needs - more than what helm2 needs, because we aren't punting it to the tiller
2. The namespace needs to be manually created

**Comment by scottyhq** [comment]
@yuvipanda - would it be unreasonable to scrap helm2 altogether and require helm>3 going forward ?

**Comment by yuvipanda** [comment]
@scottyhq hmm, maybe we can switch the default to helm3 instead? They are mostly backwards compatible...

**Comment by consideRatio** [comment]
It is my understanding that hubploy's master now use a binary named `helm`, and that everything will work if that is a helm2 or helm3 binary. Could this be correct?

**Comment by yuvipanda** [comment]
@consideRatio it defaults to that, but you can override it by setting a `HELM_EXECUTABLE` environment variable

**Comment by consideRatio** [comment]
Oh, to me this sounds very good then, and this issue would make sense to close with the summary:
- hubploy can work with a configurable helm binary (`HELM_EXECUTABLE`), but defaults to work with on called `helm`.
- hubploy will will make the right call on how to work with chosen binary depending on if it is a helm 2 or helm 3 binary
- hubploy's Dockerimage ships with helm2 available in the `helm` binary, and helm3 available in the `helm3` binary. So to use helm3 from the dockerfile, setting HELM_EXECUTABLE=helm3 is needed.

Since the original post is with support of `HELM_EXECUTABLE` added [here](https://github.com/yuvipanda/hubploy/commit/7c2f17389c27ee29582f2be005dfd6b3ab2d8db0), and by ensuring that we avoid breaking helm2/3 differences as added [here](https://github.com/yuvipanda/hubploy/commit/edf788812b2441b10b8f935ae951b5f6bd5a84d5), I'll close this issue!

Excellent work resolving this @yuvipanda! :heart:
