### ISSUE TITLE
Use AWS specific terminology in hubploy.yaml

### ISSUE THREAD

**Issue by yuvipanda** [yuvipanda/hubploy#41]
Currently it says 'project' and 'zone', should actually be 'account_id' and 'region'

**Comment by salvis2** [comment]
This would require changing:
- `hubploy.yaml` in the docs and `hubploy-template`
- [This function signature](https://github.com/yuvipanda/hubploy/blob/master/hubploy/auth.py#L80) for `registry_auth_aws` and one line in the same function
- [This function signature](https://github.com/yuvipanda/hubploy/blob/master/hubploy/auth.py#L260) for `cluster_auth_aws` and one line in the same function

Anything else? I can probably hammer this out next week unless we want to leave it as a "good first issue" for someone else.

**Comment by yuvipanda** [comment]
yeah I think that's about it.

**Comment by salvis2** [comment]
I'll update the function signatures, docs, and `hubploy-template`, but I think it'll be automatically backwards compatible! Since the functions take in their parameters [like this](https://github.com/RPVote/dssg-jhub/blob/staging/.github/workflows/deploy.yaml#L33-L36):

```
            elif provider == 'aws':
                yield from registry_auth_aws(
                    deployment, **registry['aws']
                )
```

I don't think the names of the entries in `hubploy.yaml` matter, but the order does.
