### ISSUE TITLE
Pin kubernetes version to latest

### ISSUE THREAD

**Issue by cslocum** [yuvipanda/hubploy#69]
We want to make sure we're using the latest version of kubernetes.

https://github.com/yuvipanda/hubploy/blob/master/setup.py#L12

**Comment by consideRatio** [comment]
Hi @cslocum!

I think you will get the latest version with hubploy if you didn't already have one older installed when installing hubploy. If you did have an older version of kubernetes installed already, then `pip install -U kubernetes` is probably the way to go to ensure you have the latest version.

In general, I've come to understand that the common Python practice is to avoid pinning versions or putting constraints on them unless it is clearly needed for the function of the package. For example, if hubploy would only work with a somewhat new version of a dependency, such constraints would be set, but otherwise not. This is seen here for jupyter-repo2docker for example, I guess because hubploy rely on some `repo2docker --new-flag-of-some-kind` only available since then.

https://github.com/yuvipanda/hubploy/blob/a064b2cc7847b93c77d91223db897366c8e63ad9/setup.py#L11

Cheers from Sweden
/ Erik
